exclude: ['Gemfile', 'Gemfile.lock', 'config.ru', 'README.md', 'Procfile', 'vendor', 'gems']
destination: 'public'

# Default Jekyll Config
relative_permalinks: true
permalink: pretty
permalink: /blog/:title